### ISSUE TITLE
Getting error while running 

### ISSUE THREAD

**Issue by shubham-nigam** [muratsu/capterra-reviews#5]
>node index.js
FetchError: invalid json response body at https://www.capterra.com/spotlight/rest/reviews?apiVersion=2&productId=179620 reason: Unexpected token < in JSON at position 0
    at /home/runner/HatefulCarelessMethods/node_modules/node-fetch/lib/body.js:48:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fetchReviews (/home/runner/HatefulCarelessMethods/lib.js:13:17)
    at async /home/runner/HatefulCarelessMethods/index.js:51:19 {
  type: 'invalid-json'
}

**Comment by muratsu** [comment]
Latest commit should fix this issue. Give it another shot
